FROM node:20.12-alpine
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV HOST=0.0.0.0
ENV PORT=3000
RUN corepack enable

COPY . .

RUN pnpm install --frozen-lockfile

CMD pnpm dev 
